### ISSUE TITLE
Omdb.ImdbVotes

### ISSUE THREAD

**Issue by WSHaRK993** [l3uddz/nabarr#24]
Hello,

Thanks for nabarr !

Running it on docker latest.

It looks like the filter Omdb.ImdbVotes doesn't work properly :

      ignores:
        - 'Omdb.ImdbRating < 6.0'
        - 'Omdb.ImdbVotes < 1000'

The file will always be ignored even if ImdbVotes is > 1000.

Feb 23 14:20:03 DBG Item matched ignore filters feed_name=tr feed_title=SomeMovie-Tag ignore_filter="Omdb.ImdbVotes < 1000" pvr_name=radarr pvr_type=radarr trakt_imdb_id=ttedited trakt_title="SomeMovie"

The manual API request returns "imdbVotes":"16,291" in the json.

I see imdbVotes is declared as an int in the source code. Maybe the "," is causing problems ? I don't know, I'm not familiar with Go :)

Regards,

**Comment by l3uddz** [comment]
thanks, should be resolved in latest build.
