### ISSUE TITLE
Radarr API url changed

### ISSUE THREAD

**Issue by WSHaRK993** [l3uddz/nabarr#29]
Hello,

Currently running latest docker image.

Radarr changed its API url according to https://github.com/Radarr/Radarr/pull/6344

"endpoints should now be under /api/V3/XXX rather than /api/XXX"

I now have a 404 error when running nabarr.

I don't know what are the difference between the legacy and the V3 api tough...

Thanks !

**Comment by l3uddz** [comment]
this is now supported by 0.2.0. the legacy api is no longer supported.
