### ISSUE TITLE
Feature Request: Honor *arr Import List Exclusions

### ISSUE THREAD

**Issue by arbitrarypunter** [l3uddz/nabarr#36]
Hi
I've been having a play around with this for the first time tonight. As usual to start with my filters weren't exactly what i wanted and i ended up with some ites being imported i didn't want. So i deleted them and added them to the import exclusion list. 
On the next run of nabarr they were imported again. 
I know i can exclude them through the config filters but it would be nice if nabarr could check against the import exclusion list before pushing the new item in. Would it be possible to include that in a future release please?
Thanks

**Comment by l3uddz** [comment]
Good idea, not sure why I did not think of it before!

Feature is available in the pvr-exclusions branch/docker tag and will be merged shortly.

**Comment by arbitrarypunter** [comment]
Thanks very much for the incredibly quick turn around, will give it a go.

**Comment by arbitrarypunter** [comment]
Just tested it and it's working perfectly for me. Can see in the debug log that it's finding the show in the exclusion list.

Thanks again!

**Comment by l3uddz** [comment]
No problem :) Thanks for the suggestion!
