### ISSUE TITLE
Make nabarr sonarr v4 compatible

### ISSUE THREAD

**Issue by Mangomc** [l3uddz/nabarr#42]
Hey

Few days ago i updated to sonarr v4 and now nabarr doesnt work anymore

When i try to connect to sonarr.domain.com
`Nov  1 06:55:40 ERR Failed initialising pvr error="get language profile: English: validate language profiles response: 404 Not Found" pvr=sonarr
`
When i try to connect to host (saltbox setup)
`Nov  1 07:16:23 ERR Failed initialising pvr error="validate api: request system status: Get "https://sonarr/api/v3/system/status/": GET https://sonarr/api/v3/system/status giving up after 11 attempt(s): Get "https://sonarr/api/v3/system/status/": dial tcp 172.19.0.11:443: connect: connection refused" pvr=sonarr`

Would be cool to make nabarr ready for sonarr v4, sadly a downgrad is not possible

**Comment by AliceDmaus** [comment]
Thanks. Works again :)
